# Generated by Django 2.2.14 on 2020-09-19 02:03
# Generated by Django 3.0.8 on 2020-10-03 23:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(3, 'Miercoles'), (4, 'Jueves'), (0, 'Domingo'), (5, 'Viernes'), (6, 'Sabado'), (1, 'Lunes'), (7, 'Domingo'), (2, 'Martes')], default=1, verbose_name='Dia')),                
                ('desde', models.TimeField(blank=True, null=True, verbose_name='Desde')),
                ('hasta', models.TimeField(blank=True, null=True, verbose_name='Hasta')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'Profesiones',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Sangre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, unique=True, verbose_name='Tipo de Sangre')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Sangre',
                'verbose_name_plural': 'Tipos de Sangre',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, unique=True, verbose_name='Descricpion')),
            ],
            options={
                'verbose_name': 'Titulo',
                'verbose_name_plural': 'Titulos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('sexo', models.CharField(choices=[('N', 'Ninguno'), ('M', 'Masculino'), ('F', 'Femenino')], default='N', max_length=1, verbose_name='Sexo')),
                ('civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union Libre')], default='S', max_length=1, verbose_name='Estado Civil')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
                ('hijos', models.IntegerField(default=0, verbose_name='No. hijos')),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.Ciudad')),
                ('profesion', models.ManyToManyField(to='login.Profesion')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.Provincia')),
                ('sangre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.Sangre')),
                ('titulo', models.ManyToManyField(to='login.Titulo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('sexo', models.CharField(choices=[('N', 'Ninguno'), ('M', 'Masculino'), ('F', 'Femenino')], default='N', max_length=1, verbose_name='Sexo')),
                ('civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union Libre')], default='S', max_length=1, verbose_name='Estado Civil')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
                ('consultoria', models.CharField(max_length=200, verbose_name='Nombre de consultorio')),
                ('lugar', models.CharField(max_length=100, verbose_name='Direccion de Consultorio')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Logos/', verbose_name='Logo')),
                ('registro', models.CharField(max_length=50, verbose_name='Registro Medico')),
                ('duracion', models.IntegerField(default=30, verbose_name='Duracion de Consulta')),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.Ciudad')),
                ('horario', models.ManyToManyField(to='login.Horario')),
                ('profesion', models.ManyToManyField(to='login.Profesion')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.Provincia')),
                ('titulo', models.ManyToManyField(to='login.Titulo')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Provincia'),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de Agenda')),
                ('hora', models.TimeField(default=datetime.date(2020, 9, 19), verbose_name='Hora')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo de Consulta')),
                ('estado', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Paciente')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
    ]
