# Generated by Django 3.1.1 on 2020-10-06 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201004_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(default=datetime.date(2020, 10, 6), verbose_name='Hora'),
        ),
    ]
