# Generated by Django 2.2.14 on 2020-10-04 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Diagnostico')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Domingo'), (7, 'Domingo'), (5, 'Viernes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (6, 'Sabado'), (1, 'Lunes')], default=1, verbose_name='Dia')),
                ('desde', models.TimeField(blank=True, null=True, verbose_name='Desde')),
                ('hasta', models.TimeField(blank=True, null=True, verbose_name='Hasta')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Sintoma')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sintoma',
                'verbose_name_plural': 'Sintomas',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('sexo', models.CharField(choices=[('N', 'Ninguno'), ('M', 'Masculino'), ('F', 'Femenino')], default='N', max_length=1, verbose_name='sexo')),
                ('civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union')], default='S', max_length=1, verbose_name='Estado civil')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
                ('consultoria', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=100, verbose_name='Direccion de Consultorio')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Logos/', verbose_name='Logo')),
                ('registro', models.CharField(max_length=50, verbose_name='Registro Medico')),
                ('duracion', models.IntegerField(default=30, verbose_name='Duracion de Consulta')),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appcore.Ciudad')),
                ('horario', models.ManyToManyField(to='appcore.Horario')),
                ('profesion', models.ManyToManyField(to='appcore.Profesion')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appcore.Provincia')),
                ('titulo', models.ManyToManyField(to='appcore.Titulo')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
    ]
