# Generated by Django 2.2.14 on 2020-10-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0002_diagnostico_doctor_horario_sintoma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.IntegerField(choices=[(1, 'Lunes'), (0, 'Domingo'), (4, 'Jueves'), (6, 'Sabado'), (3, 'Miercoles'), (5, 'Viernes'), (7, 'Domingo'), (2, 'Martes')], default=1, verbose_name='Dia'),
        ),
    ]
