# Generated by Django 3.1.1 on 2020-10-04 20:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0003_auto_20201004_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.IntegerField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (5, 'Viernes'), (3, 'Miercoles'), (6, 'Sabado'), (7, 'Domingo'), (4, 'Jueves')], default=1, verbose_name='Dia'),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2020, 10, 4), null=True, verbose_name='Fecha de Agenda')),
                ('hora', models.TimeField(default=datetime.time(15, 49, 16, 626369), verbose_name='Hora')),
                ('estado', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.paciente')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
    ]
